default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: qvtran
  password: vutran_513

development:
  <<: *default
  database: recipe_dev

test:
  <<: *default
  database: recipe_test

production:
  <<: *default
  database: recipe_production
